[package]
name = "typikon"
version = "0.4.0"
edition = "2024"

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[dependencies]
blake3 = "1"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
flatbuffers = "2"

[[bench]]
name = "wire"
harness = false
test = false

[[bench]]
name = "compare"
harness = false
test = false
