[build-system]
requires = ["maturin>=1.7,<2"]
build-backend = "maturin"

[project]
name = "typikon-python"
version = "0.3.1"
description = "Python binding for the Typikon binary protocol"
requires-python = ">=3.9"

[tool.maturin]
manifest-path = "Cargo.toml"
module-name = "typikon_python"
python-source = "python"
