use crate::ast::{Enum, Field, Flags, Item, Schema, Struct, Type};
use crate::fingerprint::{constructor_cid, variant_cid};

/// Generates the Rust type layer. Wire methods are added in the next codegen stage.
pub fn generate_rust(schema: &Schema) -> String {
    let mut output = String::from("// @generated by typikon; do not edit.\n\n");
    for item in &schema.items {
        match item {
            Item::Struct(item) => generate_struct(item, &mut output),
            Item::Enum(item) => generate_enum(item, &mut output),
            Item::Flags(item) => generate_flags(item, &mut output),
        }
        output.push('\n');
    }
    output
}

pub fn generate_public_schema(schema: &Schema) -> String {
    let mut output = format!("#[version({})]\n\n", schema.version);
    for item in &schema.items {
        match item {
            Item::Flags(flags) => {
                output.push_str(&format!(
                    "#[flags({})] enum {} {{ ",
                    flags.underlying, flags.name
                ));
                output.push_str(
                    &flags
                        .bits
                        .iter()
                        .map(|bit| format!("{} = {}", bit.name, bit.value))
                        .collect::<Vec<_>>()
                        .join(", "),
                );
                output.push_str(", }\n\n");
            }
            Item::Struct(item) => {
                let cid = item.cid.clone().unwrap_or_else(|| constructor_cid(item));
                output.push_str(&format!("#[cid({cid})] struct {} {{ ", item.name));
                output.push_str(
                    &item
                        .fields
                        .iter()
                        .map(|field| {
                            let guard = field
                                .guard
                                .as_ref()
                                .map(|guard| format!("#[guard({guard})] "))
                                .unwrap_or_default();
                            format!("{guard}{}: {}", field.name, schema_type(&field.ty))
                        })
                        .collect::<Vec<_>>()
                        .join(", "),
                );
                output.push_str(" }\n\n");
            }
            Item::Enum(item) => {
                output.push_str(&format!("enum {} {{ ", item.name));
                let unit_enum = item
                    .variants
                    .iter()
                    .all(|variant| variant.fields.is_empty());
                let variants = item
                    .variants
                    .iter()
                    .map(|variant| {
                        if unit_enum {
                            format!("{} = {}", variant.name, variant.value.unwrap_or_default())
                        } else {
                            let cid = variant
                                .cid
                                .clone()
                                .unwrap_or_else(|| variant_cid(item, variant));
                            let fields = variant
                                .fields
                                .iter()
                                .map(|field| format!("{}: {}", field.name, schema_type(&field.ty)))
                                .collect::<Vec<_>>()
                                .join(", ");
                            format!("#[cid({cid})] {} {{ {} }}", variant.name, fields)
                        }
                    })
                    .collect::<Vec<_>>()
                    .join(", ");
                output.push_str(&variants);
                output.push_str(", }\n\n");
            }
        }
    }
    output.pop();
    output
}

fn schema_type(ty: &Type) -> String {
    match ty {
        Type::Primitive(name) => name.clone(),
        Type::Vec(item) => format!("Vec<{}>", schema_type(item)),
        Type::Map(key, value) => format!("Map<{}, {}>", schema_type(key), schema_type(value)),
    }
}

fn generate_struct(item: &Struct, output: &mut String) {
    let cid = item.cid.clone().unwrap_or_else(|| constructor_cid(item));
    output.push_str(&format!(
        "pub const {}_CID: &str = \"{}\";\npub const {}_CID_BYTES: [u8; typikon::CID_BYTES] = {};\n",
        item.name.to_uppercase(),
        cid,
        item.name.to_uppercase(),
        cid_literal(&cid)
    ));
    output.push_str("#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]\n");
    output.push_str(&format!("pub struct {} {{\n", item.name));
    for field in &item.fields {
        output.push_str(&format!(
            "    pub {}: {},\n",
            field.name,
            rust_field_type(field)
        ));
    }
    output.push_str("}\n");
    output.push_str(&format!(
        "impl typikon::TypikonCodec for {} {{\n",
        item.name
    ));
    output.push_str("    fn encode(&self) -> Result<Vec<u8>, typikon::WireError> { typikon::encode_value(self) }\n");
    output.push_str("    fn decode(bytes: &[u8]) -> Result<Self, typikon::WireError> { let mut decoder = typikon::Decoder::new(bytes, typikon::DEFAULT_MAX_PACKET_SIZE)?; let value = <Self as typikon::WireCodec>::decode(&mut decoder)?; if decoder.is_finished() { Ok(value) } else { Err(typikon::WireError::MalformedConstructor) } }\n}\n");
    output.push_str(&format!("impl typikon::WireCodec for {} {{\n", item.name));
    output.push_str("    fn encode(&self, encoder: &mut typikon::Encoder) -> Result<(), typikon::WireError> {\n");
    output.push_str(&format!(
        "        encoder.raw(&{}_CID_BYTES)?;\n",
        item.name.to_uppercase()
    ));
    for field in &item.fields {
        if let Some(guard) = &field.guard {
            let (owner, bit) = guard.split_once('.').unwrap_or(("flags", guard));
            let owner_type = item
                .fields
                .iter()
                .find(|candidate| candidate.name == owner)
                .map(|candidate| rust_type(&candidate.ty))
                .unwrap_or_else(|| owner.to_owned());
            if is_byte_vec(&field.ty) {
                output.push_str(&format!("        if self.{owner}.contains({owner_type}::{}) {{ encoder.bytes(self.{}.as_ref().ok_or(typikon::WireError::MalformedConstructor)?)?; }}\n", const_name(bit), field.name));
            } else {
                output.push_str(&format!("        if self.{owner}.contains({owner_type}::{}) {{ self.{}.as_ref().ok_or(typikon::WireError::MalformedConstructor)?.encode(encoder)?; }}\n", const_name(bit), field.name));
            }
        } else if is_byte_vec(&field.ty) {
            output.push_str(&format!("        encoder.bytes(&self.{})?;\n", field.name));
        } else {
            output.push_str(&format!("        self.{}.encode(encoder)?;\n", field.name));
        }
    }
    output.push_str("        Ok(())\n    }\n    fn decode(decoder: &mut typikon::Decoder<'_>) -> Result<Self, typikon::WireError> {\n");
    output.push_str(&format!(
        "        decoder.expect_cid_bytes(&{}_CID_BYTES)?;\n",
        item.name.to_uppercase()
    ));
    for field in &item.fields {
        if let Some(guard) = &field.guard {
            let (owner, bit) = guard.split_once('.').unwrap_or(("flags", guard));
            let owner_type = item
                .fields
                .iter()
                .find(|candidate| candidate.name == owner)
                .map(|candidate| rust_type(&candidate.ty))
                .unwrap_or_else(|| owner.to_owned());
            let decode = if is_byte_vec(&field.ty) {
                "decoder.bytes()?".to_owned()
            } else {
                "typikon::WireCodec::decode(decoder)?".to_owned()
            };
            output.push_str(&format!("        let {}: Option<{}> = if {}.contains({}::{}) {{ Some({}) }} else {{ None }};\n", field.name, rust_type(&field.ty), owner, owner_type, const_name(bit), decode));
        } else if is_byte_vec(&field.ty) {
            output.push_str(&format!(
                "        let {}: {} = decoder.bytes()?;\n",
                field.name,
                rust_type(&field.ty)
            ));
        } else {
            output.push_str(&format!(
                "        let {}: {} = typikon::WireCodec::decode(decoder)?;\n",
                field.name,
                rust_type(&field.ty)
            ));
        }
    }
    output.push_str("        Ok(Self { ");
    output.push_str(
        &item
            .fields
            .iter()
            .map(|field| field.name.clone())
            .collect::<Vec<_>>()
            .join(", "),
    );
    output.push_str(" })\n    }\n    fn encoded_len(&self) -> usize {\n        let mut size = typikon::CID_BYTES;\n");
    for field in &item.fields {
        if let Some(guard) = &field.guard {
            let (owner, bit) = guard.split_once('.').unwrap_or(("flags", guard));
            let owner_type = item
                .fields
                .iter()
                .find(|candidate| candidate.name == owner)
                .map(|candidate| rust_type(&candidate.ty))
                .unwrap_or_else(|| owner.to_owned());
            if is_byte_vec(&field.ty) {
                output.push_str(&format!("        if self.{owner}.contains({owner_type}::{}) {{ if let Some(value) = &self.{} {{ size = size.saturating_add(typikon::varint_len(value.len() as u64)).saturating_add(value.len()); }} }}\n", const_name(bit), field.name));
            } else {
                output.push_str(&format!("        if self.{owner}.contains({owner_type}::{}) {{ if let Some(value) = &self.{} {{ size = size.saturating_add(typikon::WireCodec::encoded_len(value)); }} }}\n", const_name(bit), field.name));
            }
        } else if is_byte_vec(&field.ty) {
            output.push_str(&format!("        size = size.saturating_add(typikon::varint_len(self.{}.len() as u64)).saturating_add(self.{}.len());\n", field.name, field.name));
        } else {
            output.push_str(&format!(
                "        size = size.saturating_add(typikon::WireCodec::encoded_len(&self.{}));\n",
                field.name
            ));
        }
    }
    output.push_str("        size\n    }\n}\n");
}

fn generate_enum(item: &Enum, output: &mut String) {
    if item
        .variants
        .iter()
        .all(|variant| variant.fields.is_empty())
    {
        generate_unit_enum(item, output);
        return;
    }
    output.push_str("#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]\n");
    output.push_str(&format!("pub enum {} {{\n", item.name));
    for variant in &item.variants {
        if variant.fields.is_empty() {
            output.push_str(&format!("    {},\n", variant.name));
        } else {
            output.push_str(&format!("    {} {{\n", variant.name));
            for field in &variant.fields {
                output.push_str(&format!(
                    "        {}: {},\n",
                    field.name,
                    rust_field_type(field)
                ));
            }
            output.push_str("    },\n");
        }
    }
    output.push_str("}\n");
    for variant in &item.variants {
        let cid = variant
            .cid
            .clone()
            .unwrap_or_else(|| variant_cid(item, variant));
        output.push_str(&format!(
            "pub const {}_{}_CID: &str = \"{}\";\npub const {}_{}_CID_BYTES: [u8; typikon::CID_BYTES] = {};\n",
            item.name.to_uppercase(),
            variant.name.to_uppercase(),
            cid,
            item.name.to_uppercase(),
            variant.name.to_uppercase(),
            cid_literal(&cid)
        ));
    }
    output.push_str(&format!(
        "impl typikon::TypikonCodec for {} {{\n",
        item.name
    ));
    output.push_str("    fn encode(&self) -> Result<Vec<u8>, typikon::WireError> { typikon::encode_value(self) }\n");
    output.push_str("    fn decode(bytes: &[u8]) -> Result<Self, typikon::WireError> { let mut decoder = typikon::Decoder::new(bytes, typikon::DEFAULT_MAX_PACKET_SIZE)?; let value = <Self as typikon::WireCodec>::decode(&mut decoder)?; if decoder.is_finished() { Ok(value) } else { Err(typikon::WireError::MalformedConstructor) } }\n}\n");
    output.push_str(&format!("impl typikon::WireCodec for {} {{\n", item.name));
    output.push_str("    fn encode(&self, encoder: &mut typikon::Encoder) -> Result<(), typikon::WireError> { match self {\n");
    for variant in &item.variants {
        let cid_name = format!(
            "{}_{}_CID",
            item.name.to_uppercase(),
            variant.name.to_uppercase()
        );
        if variant.fields.is_empty() {
            output.push_str(&format!(
                "        Self::{} => {{ encoder.raw(&{cid_name}_BYTES)?; }},\n",
                variant.name
            ));
        } else {
            output.push_str(&format!(
                "        Self::{} {{ {} }} => {{ encoder.raw(&{cid_name}_BYTES)?;",
                variant.name,
                variant
                    .fields
                    .iter()
                    .map(|field| field.name.clone())
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
            for field in &variant.fields {
                if is_byte_vec(&field.ty) {
                    output.push_str(&format!(" encoder.bytes({})?;", field.name));
                } else {
                    output.push_str(&format!(" {}.encode(encoder)?;", field.name));
                }
            }
            output.push_str(" },\n");
        }
    }
    output.push_str("        } Ok(()) }\n    fn decode(decoder: &mut typikon::Decoder<'_>) -> Result<Self, typikon::WireError> { match decoder.read_cid_bytes()? {\n");
    for variant in &item.variants {
        output.push_str(&format!(
            "        {}_{}_CID_BYTES => {{",
            item.name.to_uppercase(),
            variant.name.to_uppercase()
        ));
        for field in &variant.fields {
            if is_byte_vec(&field.ty) {
                output.push_str(&format!(
                    " let {}: {} = decoder.bytes()?;",
                    field.name,
                    rust_type(&field.ty)
                ));
            } else {
                output.push_str(&format!(
                    " let {}: {} = typikon::WireCodec::decode(decoder)?;",
                    field.name,
                    rust_type(&field.ty)
                ));
            }
        }
        if variant.fields.is_empty() {
            output.push_str(&format!(" Ok(Self::{}) }},\n", variant.name));
        } else {
            output.push_str(&format!(
                " Ok(Self::{} {{ {} }}) }},\n",
                variant.name,
                variant
                    .fields
                    .iter()
                    .map(|field| field.name.clone())
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
        }
    }
    output.push_str("        _ => Err(typikon::WireError::UnknownCId), } }\n    fn encoded_len(&self) -> usize { match self {\n");
    for variant in &item.variants {
        if variant.fields.is_empty() {
            output.push_str(&format!(
                "        Self::{} => typikon::CID_BYTES,\n",
                variant.name
            ));
        } else {
            let fields = variant
                .fields
                .iter()
                .map(|field| field.name.clone())
                .collect::<Vec<_>>()
                .join(", ");
            let size = variant
                .fields
                .iter()
                .map(|field| {
                    if is_byte_vec(&field.ty) {
                        format!(".saturating_add(typikon::varint_len({}.len() as u64)).saturating_add({}.len())", field.name, field.name)
                    } else {
                        format!(
                            ".saturating_add(typikon::WireCodec::encoded_len({}))",
                            field.name
                        )
                    }
                })
                .collect::<String>();
            output.push_str(&format!(
                "        Self::{} {{ {} }} => typikon::CID_BYTES{},\n",
                variant.name, fields, size
            ));
        }
    }
    output.push_str("    } }\n}\n");
}

fn generate_unit_enum(item: &Enum, output: &mut String) {
    output.push_str("#[repr(u64)]\n#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]\n");
    output.push_str(&format!("pub enum {} {{\n", item.name));
    for variant in &item.variants {
        output.push_str(&format!(
            "    {} = {},\n",
            variant.name,
            variant.value.expect("validated unit enum value")
        ));
    }
    output.push_str("}\n");
    output.push_str(&format!(
        "impl typikon::TypikonCodec for {} {{\n",
        item.name
    ));
    output.push_str("    fn encode(&self) -> Result<Vec<u8>, typikon::WireError> { typikon::encode_value(self) }\n");
    output.push_str("    fn decode(bytes: &[u8]) -> Result<Self, typikon::WireError> { let mut decoder = typikon::Decoder::new(bytes, typikon::DEFAULT_MAX_PACKET_SIZE)?; let value = <Self as typikon::WireCodec>::decode(&mut decoder)?; if decoder.is_finished() { Ok(value) } else { Err(typikon::WireError::MalformedConstructor) } }\n}\n");
    output.push_str(&format!("impl typikon::WireCodec for {} {{\n", item.name));
    output.push_str("    fn encode(&self, encoder: &mut typikon::Encoder) -> Result<(), typikon::WireError> { encoder.u64(*self as u64) }\n");
    output.push_str("    fn decode(decoder: &mut typikon::Decoder<'_>) -> Result<Self, typikon::WireError> { match decoder.u64()? {\n");
    for variant in &item.variants {
        output.push_str(&format!(
            "        {} => Ok(Self::{}),\n",
            variant.value.expect("validated unit enum value"),
            variant.name
        ));
    }
    output.push_str("        _ => Err(typikon::WireError::InvalidEnum),\n    } }\n    fn encoded_len(&self) -> usize { 8 }\n    const FIXED_ENCODED_LEN: Option<usize> = Some(8);\n}\n");
}

fn generate_flags(item: &Flags, output: &mut String) {
    output.push_str(&format!(
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]\npub struct {}(pub {});\n",
        item.name, item.underlying
    ));
    output.push_str(&format!("impl {} {{\n", item.name));
    for bit in &item.bits {
        output.push_str(&format!(
            "    pub const {}: {} = 1 << {};\n",
            const_name(&bit.name),
            item.underlying,
            bit.value
        ));
    }
    output.push_str(&format!(
        "    pub fn contains(&self, bit: {}) -> bool {{ self.0 & bit != 0 }}\n",
        item.underlying
    ));
    output.push_str("}\n");
    let fixed_size = match item.underlying.as_str() {
        "u8" => 1,
        "u16" => 2,
        "u32" => 4,
        "u64" => 8,
        _ => unreachable!("validated flags underlying type"),
    };
    output.push_str(&format!("impl typikon::WireCodec for {} {{ const FIXED_ENCODED_LEN: Option<usize> = Some({fixed_size}); fn encode(&self, encoder: &mut typikon::Encoder) -> Result<(), typikon::WireError> {{ self.0.encode(encoder) }} fn decode(decoder: &mut typikon::Decoder<'_>) -> Result<Self, typikon::WireError> {{ Ok(Self(typikon::WireCodec::decode(decoder)?)) }} fn encoded_len(&self) -> usize {{ {fixed_size} }} }}\n", item.name));
}

fn rust_field_type(field: &Field) -> String {
    let ty = rust_type(&field.ty);
    if field.guard.is_some() {
        format!("Option<{ty}>")
    } else {
        ty
    }
}

fn rust_type(ty: &Type) -> String {
    match ty {
        Type::Primitive(name) => match name.as_str() {
            "String" => "String".into(),
            "u8" | "u16" | "u32" | "u64" | "u128" | "i8" | "i16" | "i32" | "i64" | "i128"
            | "f32" | "f64" | "bool" => name.clone(),
            other => other.into(),
        },
        Type::Vec(item) => format!("Vec<{}>", rust_type(item)),
        Type::Map(key, value) => format!(
            "std::collections::BTreeMap<{}, {}>",
            rust_type(key),
            rust_type(value)
        ),
    }
}

fn is_byte_vec(ty: &Type) -> bool {
    matches!(ty, Type::Vec(item) if matches!(item.as_ref(), Type::Primitive(name) if name == "u8"))
}

fn const_name(name: &str) -> String {
    let mut result = String::new();
    for (index, character) in name.chars().enumerate() {
        if character.is_uppercase() && index != 0 {
            result.push('_');
        }
        result.extend(character.to_uppercase());
    }
    result
}

fn cid_literal(cid: &str) -> String {
    let bytes = (0..cid.len())
        .step_by(2)
        .map(|index| format!("0x{}", &cid[index..index + 2]))
        .collect::<Vec<_>>();
    format!("[{}]", bytes.join(", "))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parse_schema;

    #[test]
    fn generates_structs_guards_and_cid() {
        let schema = parse_schema("#[version(1)] #[flags(u8)] enum F { Ready = 0, } struct Message { flags: F, #[guard(flags.ready)] value: u64, }").unwrap();
        let generated = generate_rust(&schema);
        let Item::Struct(item) = &schema.items[1] else {
            panic!()
        };
        assert!(generated.contains(&format!(
            "pub const MESSAGE_CID: &str = \"{}\";",
            constructor_cid(item)
        )));
        assert!(generated.contains("pub flags: F,"));
        assert!(generated.contains("pub value: Option<u64>,"));
        assert!(generated.contains("let value: Option<u64> = if flags.contains(F::READY)"));
        assert!(generated.contains("fn encoded_len(&self) -> usize"));
        assert!(generated.contains("size = size.saturating_add"));
    }

    #[test]
    fn generates_nested_types_and_enum_variants() {
        let schema = parse_schema(
            "#[version(1)] enum Update { New { values: Vec<Map<String, u64>>, }, Deleted, }",
        )
        .unwrap();
        let generated = generate_rust(&schema);
        assert!(generated.contains("New {"));
        assert!(generated.contains("std::collections::BTreeMap<String, u64>"));
        assert!(generated.contains("Deleted,"));
    }

    #[test]
    fn generates_bulk_codec_for_byte_vectors() {
        let schema = parse_schema(
            "#[version(1)] struct Blob { data: Vec<u8>, } enum Event { Upload { data: Vec<u8>, }, Empty, }",
        )
        .unwrap();
        let generated = generate_rust(&schema);
        assert!(generated.contains("encoder.bytes(&self.data)?;"));
        assert!(generated.contains("let data: Vec<u8> = decoder.bytes()?;"));
        assert!(generated.contains("encoder.bytes(data)?;"));
        assert!(generated.contains("varint_len(self.data.len() as u64)"));
    }

    #[test]
    fn generates_integer_wire_codec_for_unit_enum() {
        let schema =
            parse_schema("#[version(1)] enum Status { Online = 0, Offline = 1, }").unwrap();
        let generated = generate_rust(&schema);
        assert!(generated.contains("#[repr(u64)]"));
        assert!(generated.contains("encoder.u64(*self as u64)"));
        assert!(generated.contains("_ => Err(typikon::WireError::InvalidEnum)"));
        assert!(!generated.contains("STATUS_ONLINE_CID"));
    }

    #[test]
    fn generates_flags_constants() {
        let schema =
            parse_schema("#[version(1)] #[flags(u16)] enum Flags { IsBot = 0, IsPremium = 2, }")
                .unwrap();
        let generated = generate_rust(&schema);
        assert!(generated.contains("pub struct Flags(pub u16);"));
        assert!(generated.contains("pub const IS_PREMIUM: u16 = 1 << 2;"));
    }

    #[test]
    fn generates_public_schema_with_computed_cids() {
        let schema = parse_schema("#[version(10)] #[flags(u8)] enum F { Ready = 0, } struct Message { flags: F, #[guard(flags.ready)] value: Vec<u64>, } ").unwrap();
        let public = generate_public_schema(&schema);
        assert!(public.starts_with("#[version(10)]"));
        assert!(public.contains("#[flags(u8)] enum F"));
        assert!(public.contains("#[cid("));
        assert!(public.contains("#[guard(flags.ready)]"));
        assert!(public.contains("value: Vec<u64>"));
    }
}
