use crate::ast::{Enum, Field, Flags, Item, Schema, Struct, Type};
use crate::fingerprint::{constructor_cid, variant_cid};

/// Generates the Rust type layer. Wire methods are added in the next codegen stage.
pub fn generate_rust(schema: &Schema) -> String {
    let mut output = String::from("// @generated by typikon; do not edit.\n\n");
    for item in &schema.items {
        match item {
            Item::Struct(item) => generate_struct(item, schema, &mut output),
            Item::Enum(item) => generate_enum(item, schema, &mut output),
            Item::Flags(item) => generate_flags(item, &mut output),
        }
        output.push('\n');
    }
    output
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PublicSchemaFormat {
    Expanded,
    Compact,
}

pub fn generate_public_schema(schema: &Schema) -> String {
    generate_public_schema_with_format(schema, PublicSchemaFormat::Expanded)
}

pub fn generate_public_schema_compact(schema: &Schema) -> String {
    generate_public_schema_with_format(schema, PublicSchemaFormat::Compact)
}

pub fn generate_public_schema_with_format(schema: &Schema, format: PublicSchemaFormat) -> String {
    let mut output = format!("#[version({})]\n\n", schema.version);
    for item in &schema.items {
        match item {
            Item::Flags(flags) => {
                output.push_str(&format!(
                    "#[flags({})] enum {} {{ ",
                    flags.underlying, flags.name
                ));
                output.push_str(
                    &flags
                        .bits
                        .iter()
                        .map(|bit| format!("{} = {}", bit.name, bit.value))
                        .collect::<Vec<_>>()
                        .join(", "),
                );
                output.push_str(", }\n\n");
            }
            Item::Struct(item) => {
                let cid = item.cid.clone().unwrap_or_else(|| constructor_cid(item));
                if format == PublicSchemaFormat::Compact {
                    output.push_str(&format!("#[cid({cid})] struct {} {{ ", item.name));
                    output.push_str(
                        &item
                            .fields
                            .iter()
                            .map(|field| {
                                let guard = field
                                    .guard
                                    .as_ref()
                                    .map(|guard| format!("#[guard({guard})] "))
                                    .unwrap_or_default();
                                format!("{guard}{}: {}", field.name, schema_type(&field.ty))
                            })
                            .collect::<Vec<_>>()
                            .join(", "),
                    );
                    output.push_str(" }\n\n");
                } else {
                    output.push_str(&format!("#[cid({cid})]\nstruct {} {{\n", item.name));
                    for field in &item.fields {
                        let guard = field
                            .guard
                            .as_ref()
                            .map(|guard| format!("#[guard({guard})] "))
                            .unwrap_or_default();
                        output.push_str(&format!(
                            "    {guard}{}: {},\n",
                            field.name,
                            schema_type(&field.ty)
                        ));
                    }
                    output.push_str("}\n\n");
                }
            }
            Item::Enum(item) => {
                output.push_str(&format!("enum {} {{ ", item.name));
                let unit_enum = item
                    .variants
                    .iter()
                    .all(|variant| variant.fields.is_empty());
                let variants = item
                    .variants
                    .iter()
                    .map(|variant| {
                        if unit_enum {
                            format!("{} = {}", variant.name, variant.value.unwrap_or_default())
                        } else {
                            let cid = variant
                                .cid
                                .clone()
                                .unwrap_or_else(|| variant_cid(item, variant));
                            let fields = variant
                                .fields
                                .iter()
                                .map(|field| format!("{}: {}", field.name, schema_type(&field.ty)))
                                .collect::<Vec<_>>()
                                .join(", ");
                            format!("#[cid({cid})] {} {{ {} }}", variant.name, fields)
                        }
                    })
                    .collect::<Vec<_>>()
                    .join(", ");
                output.push_str(&variants);
                output.push_str(", }\n\n");
            }
        }
    }
    output.pop();
    output
}

pub(crate) fn borrowed_view_name(item: &Item, schema: &Schema) -> Option<String> {
    match item {
        Item::Struct(item) if struct_needs_borrowed(&item.name, schema, &mut Vec::new()) => {
            Some(format!("{}Ref", item.name))
        }
        Item::Enum(item)
            if !item
                .variants
                .iter()
                .all(|variant| variant.fields.is_empty())
                && enum_needs_borrowed(&item.name, schema, &mut Vec::new()) =>
        {
            Some(format!("{}Ref", item.name))
        }
        _ => None,
    }
}

fn schema_type(ty: &Type) -> String {
    match ty {
        Type::Primitive(name) => name.clone(),
        Type::Vec(item) => format!("Vec<{}>", schema_type(item)),
        Type::Map(key, value) => format!("Map<{}, {}>", schema_type(key), schema_type(value)),
    }
}

fn generate_struct(item: &Struct, schema: &Schema, output: &mut String) {
    let cid = item.cid.clone().unwrap_or_else(|| constructor_cid(item));
    output.push_str(&format!(
        "pub const {}_CID: &str = \"{}\";\npub const {}_CID_BYTES: [u8; typikon::CID_BYTES] = {};\n",
        item.name.to_uppercase(),
        cid,
        item.name.to_uppercase(),
        cid_literal(&cid)
    ));
    output.push_str("#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]\n");
    output.push_str(&format!("pub struct {} {{\n", item.name));
    for field in &item.fields {
        output.push_str(&format!(
            "    pub {}: {},\n",
            field.name,
            rust_field_type(field)
        ));
    }
    output.push_str("}\n");
    output.push_str(&format!(
        "impl typikon::TypikonCodec for {} {{\n",
        item.name
    ));
    output.push_str("    fn encode(&self) -> Result<Vec<u8>, typikon::WireError> { typikon::encode_value(self) }\n");
    output.push_str("    fn decode(bytes: &[u8]) -> Result<Self, typikon::WireError> { <Self as typikon::TypikonCodec>::decode_with_limits(bytes, typikon::DecodeLimits::default()) }\n}\n");
    output.push_str(&format!("impl typikon::WireCodec for {} {{\n", item.name));
    output.push_str("    fn encode(&self, encoder: &mut typikon::Encoder) -> Result<(), typikon::WireError> {\n");
    output.push_str(&format!(
        "        encoder.raw(&{}_CID_BYTES)?;\n",
        item.name.to_uppercase()
    ));
    for (owner, owner_type, bit, fields) in guard_groups(item) {
        let effective = format!("__typikon_effective_{owner}");
        let present = fields
            .iter()
            .map(|field| format!("self.{field}.is_some()"))
            .collect::<Vec<_>>()
            .join(" || ");
        output.push_str(&format!("        let mut {effective} = self.{owner}; if {present} {{ {effective}.0 |= {owner_type}::{bit}; }} else {{ {effective}.0 &= !{owner_type}::{bit}; }}\n"));
    }
    for field in &item.fields {
        if let Some(guard) = &field.guard {
            let (owner, bit) = guard.split_once('.').unwrap_or(("flags", guard));
            let owner_type = item
                .fields
                .iter()
                .find(|candidate| candidate.name == owner)
                .map(|candidate| rust_type(&candidate.ty))
                .unwrap_or_else(|| owner.to_owned());
            let effective = format!("__typikon_effective_{owner}");
            if is_byte_vec(&field.ty) {
                output.push_str(&format!("        if {effective}.contains({owner_type}::{}) {{ encoder.bytes(self.{}.as_ref().ok_or(typikon::WireError::MalformedConstructor)?)?; }}\n", const_name(bit), field.name));
            } else {
                output.push_str(&format!("        if {effective}.contains({owner_type}::{}) {{ self.{}.as_ref().ok_or(typikon::WireError::MalformedConstructor)?.encode(encoder)?; }}\n", const_name(bit), field.name));
            }
        } else if is_byte_vec(&field.ty) {
            output.push_str(&format!("        encoder.bytes(&self.{})?;\n", field.name));
        } else {
            let owner_has_guards = guard_groups(item)
                .iter()
                .any(|(owner, _, _, _)| owner == &field.name);
            let expr = if owner_has_guards {
                format!("__typikon_effective_{}", field.name)
            } else {
                format!("self.{}", field.name)
            };
            output.push_str(&format!("        {expr}.encode(encoder)?;\n"));
        }
    }
    output.push_str("        Ok(())\n    }\n    fn decode(decoder: &mut typikon::Decoder<'_>) -> Result<Self, typikon::WireError> {\n");
    output.push_str(&format!(
        "        decoder.expect_cid_bytes(&{}_CID_BYTES)?;\n",
        item.name.to_uppercase()
    ));
    for field in &item.fields {
        if let Some(guard) = &field.guard {
            let (owner, bit) = guard.split_once('.').unwrap_or(("flags", guard));
            let owner_type = item
                .fields
                .iter()
                .find(|candidate| candidate.name == owner)
                .map(|candidate| rust_type(&candidate.ty))
                .unwrap_or_else(|| owner.to_owned());
            let decode = if is_byte_vec(&field.ty) {
                "decoder.bytes()?".to_owned()
            } else {
                "typikon::WireCodec::decode(decoder)?".to_owned()
            };
            output.push_str(&format!("        let {}: Option<{}> = if {}.contains({}::{}) {{ Some({}) }} else {{ None }};\n", field.name, rust_type(&field.ty), owner, owner_type, const_name(bit), decode));
        } else if is_byte_vec(&field.ty) {
            output.push_str(&format!(
                "        let {}: {} = decoder.bytes()?;\n",
                field.name,
                rust_type(&field.ty)
            ));
        } else {
            output.push_str(&format!(
                "        let {}: {} = typikon::WireCodec::decode(decoder)?;\n",
                field.name,
                rust_type(&field.ty)
            ));
        }
    }
    output.push_str("        Ok(Self { ");
    output.push_str(
        &item
            .fields
            .iter()
            .map(|field| field.name.clone())
            .collect::<Vec<_>>()
            .join(", "),
    );
    output.push_str(" })\n    }\n    fn encoded_len(&self) -> usize {\n        let mut size = typikon::CID_BYTES;\n");
    for (owner, owner_type, bit, fields) in guard_groups(item) {
        let effective = format!("__typikon_effective_{owner}");
        let present = fields
            .iter()
            .map(|field| format!("self.{field}.is_some()"))
            .collect::<Vec<_>>()
            .join(" || ");
        output.push_str(&format!("        let mut {effective} = self.{owner}; if {present} {{ {effective}.0 |= {owner_type}::{bit}; }} else {{ {effective}.0 &= !{owner_type}::{bit}; }}\n"));
    }
    for field in &item.fields {
        if let Some(guard) = &field.guard {
            let (owner, bit) = guard.split_once('.').unwrap_or(("flags", guard));
            let owner_type = item
                .fields
                .iter()
                .find(|candidate| candidate.name == owner)
                .map(|candidate| rust_type(&candidate.ty))
                .unwrap_or_else(|| owner.to_owned());
            let effective = format!("__typikon_effective_{owner}");
            if is_byte_vec(&field.ty) {
                output.push_str(&format!("        if {effective}.contains({owner_type}::{}) && let Some(value) = &self.{} {{ size = size.saturating_add(typikon::varint_len(value.len() as u64)).saturating_add(value.len()); }}\n", const_name(bit), field.name));
            } else {
                output.push_str(&format!("        if {effective}.contains({owner_type}::{}) && let Some(value) = &self.{} {{ size = size.saturating_add(typikon::WireCodec::encoded_len(value)); }}\n", const_name(bit), field.name));
            }
        } else if is_byte_vec(&field.ty) {
            output.push_str(&format!("        size = size.saturating_add(typikon::varint_len(self.{}.len() as u64)).saturating_add(self.{}.len());\n", field.name, field.name));
        } else {
            output.push_str(&format!(
                "        size = size.saturating_add(typikon::WireCodec::encoded_len(&self.{}));\n",
                field.name
            ));
        }
    }
    output.push_str("        size\n    }\n}\n");
    generate_borrowed_struct(item, schema, output);
}

fn guard_groups(item: &Struct) -> Vec<(String, String, String, Vec<String>)> {
    let mut groups: Vec<(String, String, String, Vec<String>)> = Vec::new();
    for field in &item.fields {
        let Some(guard) = &field.guard else { continue };
        let (owner, bit) = guard.split_once('.').unwrap_or(("flags", guard));
        let owner_type = item
            .fields
            .iter()
            .find(|candidate| candidate.name == owner)
            .map(|candidate| rust_type(&candidate.ty))
            .unwrap_or_else(|| owner.to_owned());
        let bit = const_name(bit);
        if let Some(group) = groups
            .iter_mut()
            .find(|group| group.0 == owner && group.2 == bit)
        {
            group.3.push(field.name.clone());
        } else {
            groups.push((owner.to_owned(), owner_type, bit, vec![field.name.clone()]));
        }
    }
    groups
}

fn generate_borrowed_struct(item: &Struct, schema: &Schema, output: &mut String) {
    if !struct_needs_borrowed(&item.name, schema, &mut Vec::new()) {
        return;
    }

    output.push_str("#[derive(Debug, Clone, PartialEq)]\n");
    output.push_str(&format!("pub struct {}Ref<'a> {{\n", item.name));
    for field in &item.fields {
        output.push_str(&format!(
            "    pub {}: {},\n",
            field.name,
            borrowed_rust_field_type(field, schema)
        ));
    }
    output.push_str("}\n");
    output.push_str(&format!("impl<'a> {}Ref<'a> {{ pub fn decode_borrowed(bytes: &'a [u8]) -> Result<Self, typikon::WireError> {{ typikon::decode_borrowed_value(bytes) }} pub fn decode_borrowed_with_limits(bytes: &'a [u8], limits: typikon::DecodeLimits) -> Result<Self, typikon::WireError> {{ typikon::decode_borrowed_value_with_limits(bytes, limits) }} }}\n", item.name));
    output.push_str(&format!(
        "impl<'a> typikon::BorrowedWireCodec<'a> for {}Ref<'a> {{\n",
        item.name
    ));
    output.push_str("    fn decode_borrowed(decoder: &mut typikon::Decoder<'a>) -> Result<Self, typikon::WireError> {\n");
    output.push_str(&format!(
        "        decoder.expect_cid_bytes(&{}_CID_BYTES)?;\n",
        item.name.to_uppercase()
    ));
    for field in &item.fields {
        let decode = borrowed_decode_expression(&field.ty, schema);
        if let Some(guard) = &field.guard {
            let (owner, bit) = guard.split_once('.').unwrap_or(("flags", guard));
            let owner_type = item
                .fields
                .iter()
                .find(|candidate| candidate.name == owner)
                .map(|candidate| rust_type(&candidate.ty))
                .unwrap_or_else(|| owner.to_owned());
            output.push_str(&format!(
                "        let {}: {} = if {}.contains({}::{}) {{ Some({}) }} else {{ None }};\n",
                field.name,
                borrowed_rust_field_type(field, schema),
                owner,
                owner_type,
                const_name(bit),
                decode
            ));
        } else {
            output.push_str(&format!(
                "        let {}: {} = {};\n",
                field.name,
                borrowed_rust_field_type(field, schema),
                decode
            ));
        }
    }
    output.push_str("        Ok(Self { ");
    output.push_str(
        &item
            .fields
            .iter()
            .map(|field| field.name.clone())
            .collect::<Vec<_>>()
            .join(", "),
    );
    output.push_str(" })\n    }\n");
    output.push_str("    fn skip_borrowed(decoder: &mut typikon::Decoder<'a>) -> Result<(), typikon::WireError> {\n");
    output.push_str(&format!(
        "        decoder.expect_cid_bytes(&{}_CID_BYTES)?;\n",
        item.name.to_uppercase()
    ));
    let guard_owners = item
        .fields
        .iter()
        .filter_map(|field| field.guard.as_ref())
        .map(|guard| guard.split_once('.').unwrap_or(("flags", guard)).0)
        .collect::<Vec<_>>();
    for field in &item.fields {
        if let Some(guard) = &field.guard {
            let (owner, bit) = guard.split_once('.').unwrap_or(("flags", guard));
            let owner_type = item
                .fields
                .iter()
                .find(|candidate| candidate.name == owner)
                .map(|candidate| rust_type(&candidate.ty))
                .unwrap_or_else(|| owner.to_owned());
            output.push_str(&format!(
                "        if {owner}.contains({owner_type}::{}) {{ {} }}\n",
                const_name(bit),
                borrowed_skip_statement(&field.ty, schema)
            ));
        } else if guard_owners.iter().any(|owner| *owner == field.name) {
            output.push_str(&format!(
                "        let {}: {} = typikon::WireCodec::decode(decoder)?;\n",
                field.name,
                rust_type(&field.ty)
            ));
        } else {
            output.push_str("        ");
            output.push_str(&borrowed_skip_statement(&field.ty, schema));
            output.push('\n');
        }
    }
    output.push_str("        Ok(())\n    }\n");
    output.push_str("}\n");
}

fn generate_enum(item: &Enum, schema: &Schema, output: &mut String) {
    if item
        .variants
        .iter()
        .all(|variant| variant.fields.is_empty())
    {
        generate_unit_enum(item, output);
        return;
    }
    output.push_str("#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]\n");
    output.push_str(&format!("pub enum {} {{\n", item.name));
    for variant in &item.variants {
        if variant.fields.is_empty() {
            output.push_str(&format!("    {},\n", variant.name));
        } else {
            output.push_str(&format!("    {} {{\n", variant.name));
            for field in &variant.fields {
                output.push_str(&format!(
                    "        {}: {},\n",
                    field.name,
                    rust_field_type(field)
                ));
            }
            output.push_str("    },\n");
        }
    }
    output.push_str("}\n");
    for variant in &item.variants {
        let cid = variant
            .cid
            .clone()
            .unwrap_or_else(|| variant_cid(item, variant));
        output.push_str(&format!(
            "pub const {}_{}_CID: &str = \"{}\";\npub const {}_{}_CID_BYTES: [u8; typikon::CID_BYTES] = {};\n",
            item.name.to_uppercase(),
            variant.name.to_uppercase(),
            cid,
            item.name.to_uppercase(),
            variant.name.to_uppercase(),
            cid_literal(&cid)
        ));
    }
    output.push_str(&format!(
        "impl typikon::TypikonCodec for {} {{\n",
        item.name
    ));
    output.push_str("    fn encode(&self) -> Result<Vec<u8>, typikon::WireError> { typikon::encode_value(self) }\n");
    output.push_str("    fn decode(bytes: &[u8]) -> Result<Self, typikon::WireError> { <Self as typikon::TypikonCodec>::decode_with_limits(bytes, typikon::DecodeLimits::default()) }\n}\n");
    output.push_str(&format!("impl typikon::WireCodec for {} {{\n", item.name));
    output.push_str("    fn encode(&self, encoder: &mut typikon::Encoder) -> Result<(), typikon::WireError> { match self {\n");
    for variant in &item.variants {
        let cid_name = format!(
            "{}_{}_CID",
            item.name.to_uppercase(),
            variant.name.to_uppercase()
        );
        if variant.fields.is_empty() {
            output.push_str(&format!(
                "        Self::{} => {{ encoder.raw(&{cid_name}_BYTES)?; }},\n",
                variant.name
            ));
        } else {
            output.push_str(&format!(
                "        Self::{} {{ {} }} => {{ encoder.raw(&{cid_name}_BYTES)?;",
                variant.name,
                variant
                    .fields
                    .iter()
                    .map(|field| field.name.clone())
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
            for field in &variant.fields {
                if is_byte_vec(&field.ty) {
                    output.push_str(&format!(" encoder.bytes({})?;", field.name));
                } else {
                    output.push_str(&format!(" {}.encode(encoder)?;", field.name));
                }
            }
            output.push_str(" },\n");
        }
    }
    output.push_str("        } Ok(()) }\n    fn decode(decoder: &mut typikon::Decoder<'_>) -> Result<Self, typikon::WireError> { match decoder.read_cid_bytes()? {\n");
    for variant in &item.variants {
        output.push_str(&format!(
            "        {}_{}_CID_BYTES => {{",
            item.name.to_uppercase(),
            variant.name.to_uppercase()
        ));
        for field in &variant.fields {
            if is_byte_vec(&field.ty) {
                output.push_str(&format!(
                    " let {}: {} = decoder.bytes()?;",
                    field.name,
                    rust_type(&field.ty)
                ));
            } else {
                output.push_str(&format!(
                    " let {}: {} = typikon::WireCodec::decode(decoder)?;",
                    field.name,
                    rust_type(&field.ty)
                ));
            }
        }
        if variant.fields.is_empty() {
            output.push_str(&format!(" Ok(Self::{}) }},\n", variant.name));
        } else {
            output.push_str(&format!(
                " Ok(Self::{} {{ {} }}) }},\n",
                variant.name,
                variant
                    .fields
                    .iter()
                    .map(|field| field.name.clone())
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
        }
    }
    output.push_str("        _ => Err(typikon::WireError::UnknownCId), } }\n    fn encoded_len(&self) -> usize { match self {\n");
    for variant in &item.variants {
        if variant.fields.is_empty() {
            output.push_str(&format!(
                "        Self::{} => typikon::CID_BYTES,\n",
                variant.name
            ));
        } else {
            let fields = variant
                .fields
                .iter()
                .map(|field| field.name.clone())
                .collect::<Vec<_>>()
                .join(", ");
            let size = variant
                .fields
                .iter()
                .map(|field| {
                    if is_byte_vec(&field.ty) {
                        format!(".saturating_add(typikon::varint_len({}.len() as u64)).saturating_add({}.len())", field.name, field.name)
                    } else {
                        format!(
                            ".saturating_add(typikon::WireCodec::encoded_len({}))",
                            field.name
                        )
                    }
                })
                .collect::<String>();
            output.push_str(&format!(
                "        Self::{} {{ {} }} => typikon::CID_BYTES{},\n",
                variant.name, fields, size
            ));
        }
    }
    output.push_str("    } }\n}\n");
    generate_borrowed_enum(item, schema, output);
}

fn generate_borrowed_enum(item: &Enum, schema: &Schema, output: &mut String) {
    if !item
        .variants
        .iter()
        .flat_map(|variant| &variant.fields)
        .any(|field| borrowed_type_needs(&field.ty, schema, &mut Vec::new()))
    {
        return;
    }

    output.push_str("#[derive(Debug, Clone, PartialEq)]\n");
    output.push_str(&format!("pub enum {}Ref<'a> {{\n", item.name));
    for variant in &item.variants {
        if variant.fields.is_empty() {
            output.push_str(&format!("    {},\n", variant.name));
        } else {
            output.push_str(&format!("    {} {{\n", variant.name));
            for field in &variant.fields {
                output.push_str(&format!(
                    "        {}: {},\n",
                    field.name,
                    borrowed_rust_field_type(field, schema)
                ));
            }
            output.push_str("    },\n");
        }
    }
    output.push_str("}\n");
    output.push_str(&format!("impl<'a> {}Ref<'a> {{ pub fn decode_borrowed(bytes: &'a [u8]) -> Result<Self, typikon::WireError> {{ typikon::decode_borrowed_value(bytes) }} pub fn decode_borrowed_with_limits(bytes: &'a [u8], limits: typikon::DecodeLimits) -> Result<Self, typikon::WireError> {{ typikon::decode_borrowed_value_with_limits(bytes, limits) }} }}\n", item.name));
    output.push_str(&format!(
        "impl<'a> typikon::BorrowedWireCodec<'a> for {}Ref<'a> {{\n",
        item.name
    ));
    output.push_str("    fn decode_borrowed(decoder: &mut typikon::Decoder<'a>) -> Result<Self, typikon::WireError> { match decoder.read_cid_bytes()? {\n");
    for variant in &item.variants {
        output.push_str(&format!(
            "        {}_{}_CID_BYTES => {{",
            item.name.to_uppercase(),
            variant.name.to_uppercase()
        ));
        for field in &variant.fields {
            output.push_str(&format!(
                " let {}: {} = {};",
                field.name,
                borrowed_rust_field_type(field, schema),
                borrowed_decode_expression(&field.ty, schema)
            ));
        }
        if variant.fields.is_empty() {
            output.push_str(&format!(" Ok(Self::{}) }},\n", variant.name));
        } else {
            output.push_str(&format!(
                " Ok(Self::{} {{ {} }}) }},\n",
                variant.name,
                variant
                    .fields
                    .iter()
                    .map(|field| field.name.clone())
                    .collect::<Vec<_>>()
                    .join(", ")
            ));
        }
    }
    output.push_str("        _ => Err(typikon::WireError::UnknownCId), } }\n}\n");
}

fn generate_unit_enum(item: &Enum, output: &mut String) {
    output.push_str("#[repr(u64)]\n#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]\n");
    output.push_str(&format!("pub enum {} {{\n", item.name));
    for variant in &item.variants {
        output.push_str(&format!(
            "    {} = {},\n",
            variant.name,
            variant.value.expect("validated unit enum value")
        ));
    }
    output.push_str("}\n");
    output.push_str(&format!(
        "impl typikon::TypikonCodec for {} {{\n",
        item.name
    ));
    output.push_str("    fn encode(&self) -> Result<Vec<u8>, typikon::WireError> { typikon::encode_value(self) }\n");
    output.push_str("    fn decode(bytes: &[u8]) -> Result<Self, typikon::WireError> { <Self as typikon::TypikonCodec>::decode_with_limits(bytes, typikon::DecodeLimits::default()) }\n}\n");
    output.push_str(&format!("impl typikon::WireCodec for {} {{\n", item.name));
    output.push_str("    fn encode(&self, encoder: &mut typikon::Encoder) -> Result<(), typikon::WireError> { encoder.u64(*self as u64) }\n");
    output.push_str("    fn decode(decoder: &mut typikon::Decoder<'_>) -> Result<Self, typikon::WireError> { match decoder.u64()? {\n");
    for variant in &item.variants {
        output.push_str(&format!(
            "        {} => Ok(Self::{}),\n",
            variant.value.expect("validated unit enum value"),
            variant.name
        ));
    }
    output.push_str("        _ => Err(typikon::WireError::InvalidEnum),\n    } }\n    fn encoded_len(&self) -> usize { 8 }\n    const FIXED_ENCODED_LEN: Option<usize> = Some(8);\n}\n");
}

fn generate_flags(item: &Flags, output: &mut String) {
    output.push_str(&format!(
        "#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, serde::Deserialize)]\npub struct {}(pub {});\n",
        item.name, item.underlying
    ));
    output.push_str(&format!("impl {} {{\n", item.name));
    for bit in &item.bits {
        output.push_str(&format!(
            "    pub const {}: {} = 1 << {};\n",
            const_name(&bit.name),
            item.underlying,
            bit.value
        ));
    }
    output.push_str(&format!(
        "    pub fn contains(&self, bit: {}) -> bool {{ self.0 & bit != 0 }}\n",
        item.underlying
    ));
    output.push_str("}\n");
    let fixed_size = match item.underlying.as_str() {
        "u8" => 1,
        "u16" => 2,
        "u32" => 4,
        "u64" => 8,
        _ => unreachable!("validated flags underlying type"),
    };
    output.push_str(&format!("impl typikon::WireCodec for {} {{ const FIXED_ENCODED_LEN: Option<usize> = Some({fixed_size}); fn encode(&self, encoder: &mut typikon::Encoder) -> Result<(), typikon::WireError> {{ self.0.encode(encoder) }} fn decode(decoder: &mut typikon::Decoder<'_>) -> Result<Self, typikon::WireError> {{ Ok(Self(typikon::WireCodec::decode(decoder)?)) }} fn encoded_len(&self) -> usize {{ {fixed_size} }} }}\n", item.name));
}

fn rust_field_type(field: &Field) -> String {
    let ty = rust_type(&field.ty);
    if field.guard.is_some() {
        format!("Option<{ty}>")
    } else {
        ty
    }
}

fn borrowed_rust_field_type(field: &Field, schema: &Schema) -> String {
    let ty = borrowed_type(&field.ty, schema);
    if field.guard.is_some() {
        format!("Option<{ty}>")
    } else {
        ty
    }
}

fn borrowed_decode_expression(ty: &Type, schema: &Schema) -> String {
    match ty {
        Type::Primitive(name) if name == "String" => "decoder.string_borrowed()?".into(),
        ty if is_byte_vec(ty) => "decoder.bytes_borrowed()?".into(),
        Type::Vec(_) => "decoder.borrowed_vec()?".into(),
        Type::Map(_, _) => "decoder.borrowed_map()?".into(),
        Type::Primitive(name) if named_needs_borrowed(name, schema, &mut Vec::new()) => {
            "typikon::BorrowedWireCodec::decode_borrowed(decoder)?".into()
        }
        _ => "typikon::WireCodec::decode(decoder)?".into(),
    }
}

fn borrowed_skip_statement(ty: &Type, schema: &Schema) -> String {
    match ty {
        Type::Primitive(name) if name == "String" => "decoder.skip_string()?;".into(),
        ty if is_byte_vec(ty) => "decoder.skip_bytes()?;".into(),
        Type::Vec(item) => format!("decoder.skip_vec::<{}>()?;", borrowed_type(item, schema)),
        Type::Map(key, value) => format!(
            "decoder.skip_map::<{}, {}>()?;",
            borrowed_type(key, schema),
            borrowed_type(value, schema)
        ),
        Type::Primitive(name) if named_needs_borrowed(name, schema, &mut Vec::new()) => format!(
            "<{}Ref<'a> as typikon::BorrowedWireCodec<'a>>::skip_borrowed(decoder)?;",
            name
        ),
        _ => format!(
            "let _: {} = typikon::WireCodec::decode(decoder)?;",
            rust_type(ty)
        ),
    }
}

fn borrowed_type(ty: &Type, schema: &Schema) -> String {
    match ty {
        Type::Primitive(name) if name == "String" => "&'a str".into(),
        ty if is_byte_vec(ty) => "&'a [u8]".into(),
        Type::Primitive(name) if named_needs_borrowed(name, schema, &mut Vec::new()) => {
            format!("{name}Ref<'a>")
        }
        Type::Vec(item) => format!("typikon::BorrowedVec<'a, {}>", borrowed_type(item, schema)),
        Type::Map(key, value) => format!(
            "typikon::BorrowedMap<'a, {}, {}>",
            borrowed_type(key, schema),
            borrowed_type(value, schema)
        ),
        _ => rust_type(ty),
    }
}

fn struct_needs_borrowed(name: &str, schema: &Schema, visiting: &mut Vec<String>) -> bool {
    if visiting.iter().any(|current| current == name) {
        return false;
    }
    let Some(Item::Struct(item)) = schema.items.iter().find(|item| match item {
        Item::Struct(item) => item.name == name,
        _ => false,
    }) else {
        return false;
    };
    visiting.push(name.to_owned());
    let needs = item
        .fields
        .iter()
        .any(|field| borrowed_type_needs(&field.ty, schema, visiting));
    visiting.pop();
    needs
}

fn borrowed_type_needs(ty: &Type, schema: &Schema, visiting: &mut Vec<String>) -> bool {
    match ty {
        Type::Primitive(name) if name == "String" => true,
        ty if is_byte_vec(ty) => true,
        Type::Primitive(name) => named_needs_borrowed(name, schema, visiting),
        Type::Vec(_) | Type::Map(_, _) => true,
    }
}

fn named_needs_borrowed(name: &str, schema: &Schema, visiting: &mut Vec<String>) -> bool {
    struct_needs_borrowed(name, schema, visiting) || enum_needs_borrowed(name, schema, visiting)
}

fn enum_needs_borrowed(name: &str, schema: &Schema, visiting: &mut Vec<String>) -> bool {
    if visiting.iter().any(|current| current == name) {
        return false;
    }
    let Some(Item::Enum(item)) = schema.items.iter().find(|item| match item {
        Item::Enum(item) => item.name == name,
        _ => false,
    }) else {
        return false;
    };
    visiting.push(name.to_owned());
    let needs = item.variants.iter().any(|variant| {
        variant
            .fields
            .iter()
            .any(|field| borrowed_type_needs(&field.ty, schema, visiting))
    });
    visiting.pop();
    needs
}

fn rust_type(ty: &Type) -> String {
    match ty {
        Type::Primitive(name) => match name.as_str() {
            "String" => "String".into(),
            "u8" | "u16" | "u32" | "u64" | "u128" | "i8" | "i16" | "i32" | "i64" | "i128"
            | "f32" | "f64" | "bool" => name.clone(),
            other => other.into(),
        },
        Type::Vec(item) => format!("Vec<{}>", rust_type(item)),
        Type::Map(key, value) => format!(
            "std::collections::BTreeMap<{}, {}>",
            rust_type(key),
            rust_type(value)
        ),
    }
}

fn is_byte_vec(ty: &Type) -> bool {
    matches!(ty, Type::Vec(item) if matches!(item.as_ref(), Type::Primitive(name) if name == "u8"))
}

fn const_name(name: &str) -> String {
    let mut result = String::new();
    for (index, character) in name.chars().enumerate() {
        if character.is_uppercase() && index != 0 {
            result.push('_');
        }
        result.extend(character.to_uppercase());
    }
    result
}

fn cid_literal(cid: &str) -> String {
    let bytes = (0..cid.len())
        .step_by(2)
        .map(|index| format!("0x{}", &cid[index..index + 2]))
        .collect::<Vec<_>>();
    format!("[{}]", bytes.join(", "))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parse_schema;

    #[test]
    fn generates_structs_guards_and_cid() {
        let schema = parse_schema("#[version(1)] #[flags(u8)] enum F { Ready = 0, } struct Message { flags: F, #[guard(flags.ready)] value: u64, }").unwrap();
        let generated = generate_rust(&schema);
        let Item::Struct(item) = &schema.items[1] else {
            panic!()
        };
        assert!(generated.contains(&format!(
            "pub const MESSAGE_CID: &str = \"{}\";",
            constructor_cid(item)
        )));
        assert!(generated.contains("pub flags: F,"));
        assert!(generated.contains("pub value: Option<u64>,"));
        assert!(generated.contains("let value: Option<u64> = if flags.contains(F::READY)"));
        assert!(generated.contains("fn encoded_len(&self) -> usize"));
        assert!(generated.contains("size = size.saturating_add"));
    }

    #[test]
    fn generates_nested_types_and_enum_variants() {
        let schema = parse_schema(
            "#[version(1)] enum Update { New { values: Vec<Map<String, u64>>, }, Deleted, }",
        )
        .unwrap();
        let generated = generate_rust(&schema);
        assert!(generated.contains("New {"));
        assert!(generated.contains("std::collections::BTreeMap<String, u64>"));
        assert!(generated.contains("Deleted,"));
    }

    #[test]
    fn generates_bulk_codec_for_byte_vectors() {
        let schema = parse_schema(
            "#[version(1)] struct Blob { name: String, data: Vec<u8>, } enum Event { Upload { data: Vec<u8>, }, Empty, }",
        )
        .unwrap();
        let generated = generate_rust(&schema);
        assert!(generated.contains("encoder.bytes(&self.data)?;"));
        assert!(generated.contains("let data: Vec<u8> = decoder.bytes()?;"));
        assert!(generated.contains("encoder.bytes(data)?;"));
        assert!(generated.contains("varint_len(self.data.len() as u64)"));
        assert!(generated.contains("pub struct BlobRef<'a>"));
        assert!(generated.contains("pub name: &'a str"));
        assert!(generated.contains("pub data: &'a [u8]"));
        assert!(generated.contains("decoder.string_borrowed()?"));
        assert!(generated.contains("decoder.bytes_borrowed()?"));
    }

    #[test]
    fn guard_bits_follow_option_presence_during_encode_and_length() {
        let schema = parse_schema(
            "#[version(1)] #[flags(u16)] enum Flags { HasAvatar = 2, } struct User { flags: Flags, #[guard(flags.has_avatar)] avatar: String, }",
        )
        .unwrap();
        let generated = generate_rust(&schema);
        assert!(generated.contains(
            "if self.avatar.is_some() { __typikon_effective_flags.0 |= Flags::HAS_AVATAR; }"
        ));
        assert!(generated.contains("if __typikon_effective_flags.contains(Flags::HAS_AVATAR)"));
        assert!(
            generated
                .matches("let mut __typikon_effective_flags")
                .count()
                >= 2
        );
    }

    #[test]
    fn propagates_borrowed_views_through_named_structs() {
        let schema = parse_schema(
            "#[version(1)] struct User { username: String, } struct Message { sender: User, text: String, }",
        )
        .unwrap();
        let generated = generate_rust(&schema);
        assert!(generated.contains("pub struct UserRef<'a>"));
        assert!(generated.contains("pub struct MessageRef<'a>"));
        assert!(generated.contains("pub sender: UserRef<'a>"));
        assert!(generated.contains("typikon::BorrowedWireCodec::decode_borrowed(decoder)?"));
        assert!(generated.contains("fn skip_borrowed(decoder: &mut typikon::Decoder<'a>)"));
        assert!(generated.contains("decoder.skip_string()?"));
    }

    #[test]
    fn generates_lazy_borrowed_collection_views() {
        let schema = parse_schema(
            "#[version(1)] struct Packet { labels: Vec<String>, metadata: Map<String, String>, }",
        )
        .unwrap();
        let generated = generate_rust(&schema);
        assert!(generated.contains("pub labels: typikon::BorrowedVec<'a, &'a str>"));
        assert!(generated.contains("pub metadata: typikon::BorrowedMap<'a, &'a str, &'a str>"));
        assert!(generated.contains("decoder.borrowed_vec()?"));
        assert!(generated.contains("decoder.borrowed_map()?"));
    }

    #[test]
    fn generates_borrowed_enum_payload_views() {
        let schema = parse_schema(
            "#[version(1)] enum Event { Text { body: String, }, Data { chunks: Vec<Vec<u8>>, }, Empty, }",
        )
        .unwrap();
        let generated = generate_rust(&schema);
        assert!(generated.contains("pub enum EventRef<'a>"));
        assert!(generated.contains("body: &'a str"));
        assert!(generated.contains("chunks: typikon::BorrowedVec<'a, &'a [u8]>"));
        assert!(generated.contains("impl<'a> typikon::BorrowedWireCodec<'a> for EventRef<'a>"));
        assert!(generated.contains("match decoder.read_cid_bytes()?"));
    }

    #[test]
    fn generates_integer_wire_codec_for_unit_enum() {
        let schema =
            parse_schema("#[version(1)] enum Status { Online = 0, Offline = 1, }").unwrap();
        let generated = generate_rust(&schema);
        assert!(generated.contains("#[repr(u64)]"));
        assert!(generated.contains("encoder.u64(*self as u64)"));
        assert!(generated.contains("_ => Err(typikon::WireError::InvalidEnum)"));
        assert!(!generated.contains("STATUS_ONLINE_CID"));
    }

    #[test]
    fn generates_flags_constants() {
        let schema =
            parse_schema("#[version(1)] #[flags(u16)] enum Flags { IsBot = 0, IsPremium = 2, }")
                .unwrap();
        let generated = generate_rust(&schema);
        assert!(generated.contains("pub struct Flags(pub u16);"));
        assert!(generated.contains("pub const IS_PREMIUM: u16 = 1 << 2;"));
    }

    #[test]
    fn generates_public_schema_with_computed_cids() {
        let schema = parse_schema("#[version(10)] #[flags(u8)] enum F { Ready = 0, } struct Message { flags: F, #[guard(flags.ready)] value: Vec<u64>, } ").unwrap();
        let public = generate_public_schema(&schema);
        let compact = generate_public_schema_compact(&schema);
        assert!(public.starts_with("#[version(10)]"));
        assert!(public.contains("#[flags(u8)] enum F"));
        assert!(public.contains("#[cid("));
        assert!(public.contains("#[guard(flags.ready)]"));
        assert!(public.contains("value: Vec<u64>"));
        assert!(public.contains("#[cid(") && public.contains("\nstruct Message {\n"));
        assert!(compact.contains("struct Message { ") && !compact.contains("\nstruct Message {\n"));
    }
}
